### ISSUE TITLE
Cannot find satisfied version of python_world

### ISSUE THREAD

**Issue by emiltoft** [ceddlyburge/python_hello_world#1]
Hi 
I get an error when trying to pip install python_hello_world.
ERROR: Could not find a version that satisfies the requirement python_world>=0.0 (from python-hello==0.0.1) (from versions: none)
ERROR: No matching distribution found for python_world>=0.0 (from python-hello==0.0.1)

I'm using python 3.6.6 and pip 19.3.1. It works fine if using "python setup.py install"

**Comment by emiltoft** [comment]
I found a solution on stackoverflow:
https://stackoverflow.com/questions/3472430/how-can-i-make-setuptools-install-a-package-thats-not-on-pypi

In the setup.py use the following for the "install_requires" and drop the "dependency_links":

setup(
   ...
   install_requires = [
   ...
   'python_world @ git+https://github.com/ceddlyburge/python_world#egg=python_world-0.0.1',
   ...
   ]
)

**Comment by ceddlyburge** [comment]
Hi there, thanks for bringing this up, and fixing it! I assume that this is due to a more recent version of pip than the one I was using. I'll update the blog post and repo when I get time. Cheers, cedd

**Comment by ceddlyburge** [comment]
Hi There, I have confirmed this behaviour.

The existing code works in pip 18 but not pip 19.

I have made the changes you suggested which makes it work for pip 19.

There is a change in functionality, in that pip no longer knows about version numbers, so can't do dependency management.

I have updated the blog post (on medium and freecodecamp) so that it makes sense for pip 19

Thanks for your help
